language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"

branches:
  only:
    - master

sudo: false

install: pip install tox coveralls

script: tox --skip-missing-interpreters

after_success: coveralls
