language: python
python:
  - "3.4"

branches:
  only:
    - master

sudo: false

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy

install: pip install tox coveralls

script: tox

after_success: coveralls
